modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_shops_mod"
version="1.0.0"
displayName="Minecraft Shops Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://discord.gg/SWx2JxfNCw"
logoFile="logo.png"
authors="Nehuel, MCreator, Markverb1"
description='''
Mod for the Minecraft shops server.
'''

[[dependencies.minecraft_shops_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




